# Generated by Django 5.0.6 on 2024-07-13 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutor', '0006_alter_classchoice_name_alter_subjectchoice_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the tuition', max_length=100)),
                ('availability', models.BooleanField(default=True, help_text='Availability status of the tuition')),
                ('description', models.TextField(help_text='Detailed description of the tuition')),
                ('medium', models.CharField(choices=[('Bangla', 'Bangla_Medium'), ('English', 'English_Version')], help_text='Medium of instruction', max_length=50)),
                ('student_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='Gender of students', max_length=50)),
                ('preferred_tutor_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='Preferred gender of tutor', max_length=50)),
                ('number_of_students', models.PositiveIntegerField(default=1, help_text='Number of students')),
                ('salary', models.DecimalField(decimal_places=2, help_text='Salary offered per month', max_digits=10)),
                ('subjects', models.ManyToManyField(help_text='Subjects taught in this tuition', to='tutor.subjectchoice')),
                ('tuition_class', models.ForeignKey(help_text='Class for which tuition is offered', on_delete=django.db.models.deletion.CASCADE, to='tutor.classchoice')),
                ('tutoring_time', models.OneToOneField(help_text='Time for tutoring', on_delete=django.db.models.deletion.CASCADE, to='tutor.timechoice')),
            ],
        ),
    ]
