# Generated by Django 5.0.6 on 2024-07-13 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Class_1', 'Class 1'), ('Class_2', 'Class 2'), ('Class_3', 'Class 3'), ('Class_4', 'Class 4'), ('Class_5', 'Class 5'), ('Class_6', 'Class 6'), ('Class_7', 'Class 7'), ('Class_8', 'Class 8'), ('Class_9', 'Class 9'), ('Class_10', 'Class 10'), ('HSC_1', 'HSC-1st_Year'), ('HSC_2', 'HSC-2nd_Year')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('General_Math', 'General Math'), ('Bangla', 'Bangla'), ('English', 'English'), ('General_Science', 'General Science'), ('Religion', 'Religion'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Higher_Math', 'Higher Math')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='tuition',
            name='tuition_class',
            field=models.ForeignKey(help_text='Class for which tuition is offered', on_delete=django.db.models.deletion.CASCADE, to='tution.classchoice'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='subjects',
            field=models.ManyToManyField(help_text='Subjects taught in this tuition', to='tution.subjectchoice'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='tutoring_time',
            field=models.OneToOneField(help_text='Time for tutoring', on_delete=django.db.models.deletion.CASCADE, to='tution.timechoice'),
        ),
    ]
