# Generated by Django 5.0.6 on 2024-07-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0002_classchoice_subjectchoice_timechoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='tuition_class',
            field=models.CharField(choices=[('Class_1', 'Class 1'), ('Class_2', 'Class 2'), ('Class_3', 'Class 3'), ('Class_4', 'Class 4'), ('Class_5', 'Class 5'), ('Class_6', 'Class 6'), ('Class_7', 'Class 7'), ('Class_8', 'Class 8'), ('Class_9', 'Class 9'), ('Class_10', 'Class 10'), ('HSC_1', 'HSC-1st_Year'), ('HSC_2', 'HSC-2nd_Year')], help_text='Class for which tuition is offered', max_length=50),
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='tuition',
            name='tutoring_time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], help_text='Time for tutoring', max_length=20),
        ),
        migrations.DeleteModel(
            name='ClassChoice',
        ),
        migrations.DeleteModel(
            name='SubjectChoice',
        ),
        migrations.AddField(
            model_name='tuition',
            name='subjects',
            field=models.CharField(choices=[('General_Math', 'General Math'), ('Bangla', 'Bangla'), ('English', 'English'), ('General_Science', 'General Science'), ('Religion', 'Religion'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Higher_Math', 'Higher Math')], default=1, help_text='Subjects taught in this tuition', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TimeChoice',
        ),
    ]
