# Generated by Django 5.0.6 on 2024-07-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0003_alter_tuition_tuition_class_remove_tuition_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('General_Math', 'General Math'), ('Bangla', 'Bangla'), ('English', 'English'), ('General_Science', 'General Science'), ('Religion', 'Religion'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Higher_Math', 'Higher Math')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='subjects',
        ),
        migrations.AddField(
            model_name='tuition',
            name='subjects',
            field=models.ManyToManyField(help_text='Subjects taught in this tuition', related_name='tuitions', to='tution.subjectchoice'),
        ),
    ]
