# Generated by Django 5.0.6 on 2024-07-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0004_subjectchoice_remove_tuition_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectchoice',
            name='name',
            field=models.CharField(choices=[('General_Math', 'General Math'), ('Bangla', 'Bangla'), ('English', 'English'), ('General_Science', 'General Science'), ('Religion', 'Religion'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Higher_Math', 'Higher Math'), ('All_Subjects', 'All Subjects')], max_length=50),
        ),
    ]
