# Generated by Django 5.0.6 on 2024-07-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0006_alter_tuition_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='tuition_class',
            field=models.CharField(choices=[('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('Class 7', 'Class 7'), ('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10'), ('HSC 1', 'HSC-1st_Year'), ('HSC 2', 'HSC-2nd_Year')], help_text='Class for which tuition is offered', max_length=50),
        ),
    ]
