# Generated by Django 5.0.6 on 2024-07-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0007_alter_tuition_tuition_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
