# Generated by Django 5.0.6 on 2024-07-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0009_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('⭐', 1), ('⭐⭐', 2), ('⭐⭐⭐', 3), ('⭐⭐⭐⭐', 4), ('⭐⭐⭐⭐⭐', 5)], max_length=10),
        ),
    ]
