# Generated by Django 5.0.6 on 2024-07-16 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0010_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tuition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tution.tuition'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], max_length=10),
        ),
    ]
