# Generated by Django 5.0.6 on 2024-07-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0011_review_tuition_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tuition',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('⭐', 1), ('⭐⭐', 2), ('⭐⭐⭐', 3), ('⭐⭐⭐⭐', 4), ('⭐⭐⭐⭐⭐', 5)], max_length=10),
        ),
    ]
