# Generated by Django 5.0.6 on 2024-08-15 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0001_initial'),
        ('tution', '0013_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.adminmodel'),
            preserve_default=False,
        ),
    ]
