# Generated by Django 5.0.6 on 2024-08-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0014_tuition_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tuition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tution.tuition'),
        ),
    ]
