# Generated by Django 5.0.6 on 2024-07-13 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('tuition_district', models.CharField(max_length=100)),
                ('preferred_area', models.CharField(max_length=100)),
                ('minimum_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=20)),
                ('days_per_week', models.IntegerField(default=5)),
                ('tutoring_experience', models.CharField(max_length=20)),
                ('extra_facilities', models.CharField(max_length=200)),
                ('medium_of_instruction', models.CharField(choices=[('Bangla', 'Bangla Medium'), ('English', 'English Version')], max_length=20)),
                ('preferred_class', models.CharField(choices=[('Class 1', 'Class 1 (Bangla Medium)'), ('Class 2', 'Class 2 (Bangla Medium)'), ('Class 3', 'Class 3 (Bangla Medium)'), ('Class 4', 'Class 4 (Bangla Medium)'), ('Class 5', 'Class 5 (Bangla Medium)'), ('Class 6', 'Class 6 (Bangla Medium)'), ('Class 7', 'Class 7 (Bangla Medium)'), ('Class 8', 'Class 8 (Bangla Medium)'), ('Class 9', 'Class 9 (Bangla Medium)'), ('Class 10', 'Class 10 (Bangla Medium)'), ('HSC-1st YEAR', 'HSC-1st YEAR (Bangla Medium)'), ('HSC-2nd YEAR', 'HSC-2nd YEAR (Bangla Medium)')], max_length=50)),
                ('preferred_subjects', models.CharField(choices=[('General Math', 'General Math (Class 1)'), ('Bangla', 'Bangla (Class 1)'), ('English', 'English (Class 1)'), ('General Science', 'General Science (Class 1)'), ('Religion', 'Religion (Class 1)'), ('General Math', 'General Math (Class 2)'), ('Bangla', 'Bangla (Class 2)'), ('English', 'English (Class 2)'), ('General Science', 'General Science (Class 2)'), ('Religion', 'Religion (Class 2)'), ('General Math', 'General Math (Class 3)'), ('Bangla', 'Bangla (Class 3)'), ('English', 'English (Class 3)'), ('General Science', 'General Science (Class 3)'), ('Religion', 'Religion (Class 3)'), ('General Math', 'General Math (Class 4)'), ('Bangla', 'Bangla (Class 4)'), ('English', 'English (Class 4)'), ('General Science', 'General Science (Class 4)'), ('Religion', 'Religion (Class 4)'), ('General Math', 'General Math (Class 5)'), ('Bangla', 'Bangla (Class 5)'), ('English', 'English (Class 5)'), ('General Science', 'General Science (Class 5)'), ('Religion', 'Religion (Class 5)'), ('General Math', 'General Math (Class 6)'), ('Bangla', 'Bangla (Class 6)'), ('English', 'English (Class 6)'), ('General Science', 'General Science (Class 6)'), ('Religion', 'Religion (Class 6)'), ('General Math', 'General Math (Class 7)'), ('Bangla', 'Bangla (Class 7)'), ('English', 'English (Class 7)'), ('General Science', 'General Science (Class 7)'), ('Religion', 'Religion (Class 7)'), ('General Math', 'General Math (Class 8)'), ('Bangla', 'Bangla (Class 8)'), ('English', 'English (Class 8)'), ('General Science', 'General Science (Class 8)'), ('Religion', 'Religion (Class 8)'), ('General Math', 'General Math (Class 9)'), ('Bangla', 'Bangla (Class 9)'), ('English', 'English (Class 9)'), ('General Science', 'General Science (Class 9)'), ('Religion', 'Religion (Class 9)'), ('General Math', 'General Math (Class 10)'), ('Bangla', 'Bangla (Class 10)'), ('English', 'English (Class 10)'), ('General Science', 'General Science (Class 10)'), ('Religion', 'Religion (Class 10)'), ('Physics', 'Physics (HSC-1st YEAR)'), ('Chemistry', 'Chemistry (HSC-1st YEAR)'), ('Biology', 'Biology (HSC-1st YEAR)'), ('Higher Math', 'Higher Math (HSC-1st YEAR)'), ('Physics', 'Physics (HSC-2nd YEAR)'), ('Chemistry', 'Chemistry (HSC-2nd YEAR)'), ('Biology', 'Biology (HSC-2nd YEAR)'), ('Higher Math', 'Higher Math (HSC-2nd YEAR)')], max_length=50)),
                ('preferred_time', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20)),
                ('preferred_area_to_teach', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_Name', models.CharField(max_length=50)),
                ('passing_year', models.IntegerField()),
                ('institution', models.CharField(max_length=100)),
                ('Group', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=10)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='tutor.tutormodel')),
            ],
        ),
        migrations.CreateModel(
            name='TutorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tutor.tutormodel')),
            ],
        ),
    ]
