# Generated by Django 5.0.6 on 2024-09-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutormodel',
            old_name='subjects',
            new_name='subject',
        ),
    ]
