# Generated by Django 5.0.6 on 2024-07-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_alter_tutormodel_minimum_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Class 1', 'Class 1 (Bangla Medium)'), ('Class 2', 'Class 2 (Bangla Medium)'), ('Class 3', 'Class 3 (Bangla Medium)'), ('Class 4', 'Class 4 (Bangla Medium)'), ('Class 5', 'Class 5 (Bangla Medium)'), ('Class 6', 'Class 6 (Bangla Medium)'), ('Class 7', 'Class 7 (Bangla Medium)'), ('Class 8', 'Class 8 (Bangla Medium)'), ('Class 9', 'Class 9 (Bangla Medium)'), ('Class 10', 'Class 10 (Bangla Medium)'), ('HSC-1st YEAR', 'HSC-1st YEAR (Bangla Medium)'), ('HSC-2nd YEAR', 'HSC-2nd YEAR (Bangla Medium)')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('General Math', 'General Math (Class 1)'), ('Bangla', 'Bangla (Class 1)'), ('English', 'English (Class 1)'), ('General Science', 'General Science (Class 1)'), ('Religion', 'Religion (Class 1)'), ('General Math', 'General Math (Class 2)'), ('Bangla', 'Bangla (Class 2)'), ('English', 'English (Class 2)'), ('General Science', 'General Science (Class 2)'), ('Religion', 'Religion (Class 2)'), ('General Math', 'General Math (Class 3)'), ('Bangla', 'Bangla (Class 3)'), ('English', 'English (Class 3)'), ('General Science', 'General Science (Class 3)'), ('Religion', 'Religion (Class 3)'), ('General Math', 'General Math (Class 4)'), ('Bangla', 'Bangla (Class 4)'), ('English', 'English (Class 4)'), ('General Science', 'General Science (Class 4)'), ('Religion', 'Religion (Class 4)'), ('General Math', 'General Math (Class 5)'), ('Bangla', 'Bangla (Class 5)'), ('English', 'English (Class 5)'), ('General Science', 'General Science (Class 5)'), ('Religion', 'Religion (Class 5)'), ('General Math', 'General Math (Class 6)'), ('Bangla', 'Bangla (Class 6)'), ('English', 'English (Class 6)'), ('General Science', 'General Science (Class 6)'), ('Religion', 'Religion (Class 6)'), ('General Math', 'General Math (Class 7)'), ('Bangla', 'Bangla (Class 7)'), ('English', 'English (Class 7)'), ('General Science', 'General Science (Class 7)'), ('Religion', 'Religion (Class 7)'), ('General Math', 'General Math (Class 8)'), ('Bangla', 'Bangla (Class 8)'), ('English', 'English (Class 8)'), ('General Science', 'General Science (Class 8)'), ('Religion', 'Religion (Class 8)'), ('General Math', 'General Math (Class 9)'), ('Bangla', 'Bangla (Class 9)'), ('English', 'English (Class 9)'), ('General Science', 'General Science (Class 9)'), ('Religion', 'Religion (Class 9)'), ('General Math', 'General Math (Class 10)'), ('Bangla', 'Bangla (Class 10)'), ('English', 'English (Class 10)'), ('General Science', 'General Science (Class 10)'), ('Religion', 'Religion (Class 10)'), ('Physics', 'Physics (HSC-1st YEAR)'), ('Chemistry', 'Chemistry (HSC-1st YEAR)'), ('Biology', 'Biology (HSC-1st YEAR)'), ('Higher Math', 'Higher Math (HSC-1st YEAR)'), ('Physics', 'Physics (HSC-2nd YEAR)'), ('Chemistry', 'Chemistry (HSC-2nd YEAR)'), ('Biology', 'Biology (HSC-2nd YEAR)'), ('Higher Math', 'Higher Math (HSC-2nd YEAR)')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutormodel',
            name='preferred_class',
        ),
        migrations.RemoveField(
            model_name='tutormodel',
            name='preferred_subjects',
        ),
        migrations.RemoveField(
            model_name='tutormodel',
            name='preferred_time',
        ),
        migrations.AddField(
            model_name='tutormodel',
            name='preferred_class',
            field=models.ManyToManyField(to='tutor.classchoice'),
        ),
        migrations.AddField(
            model_name='tutormodel',
            name='preferred_subjects',
            field=models.ManyToManyField(to='tutor.subjectchoice'),
        ),
        migrations.AddField(
            model_name='tutormodel',
            name='preferred_time',
            field=models.ManyToManyField(to='tutor.timechoice'),
        ),
    ]
