# Generated by Django 5.0.6 on 2024-10-31 09:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_remove_tutormodel_subject_tutormodel_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutormodel',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder_image_public_id', max_length=255, verbose_name='image'),
        ),
    ]
