# Generated by Django 5.0.6 on 2024-07-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_classchoice_subjectchoice_timechoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutormodel',
            name='preferred_area',
        ),
    ]
