# Generated by Django 5.0.6 on 2024-07-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_tutormodel_image_alter_tutorreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classchoice',
            name='name',
            field=models.CharField(choices=[('Class_1', 'Class 1'), ('Class_2', 'Class 2'), ('Class_3', 'Class 3'), ('Class_4', 'Class 4'), ('Class_5', 'Class 5'), ('Class_6', 'Class 6'), ('Class_7', 'Class 7'), ('Class_8', 'Class 8'), ('Class_9', 'Class 9'), ('Class_10', 'Class 10'), ('HSC_1', 'HSC-1st_Year'), ('HSC_2', 'HSC-2nd_Year')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectchoice',
            name='name',
            field=models.CharField(choices=[('General_Math', 'General Math'), ('Bangla', 'Bangla'), ('English', 'English'), ('General_Science', 'General Science'), ('Religion', 'Religion'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Higher_Math', 'Higher Math')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='medium_of_instruction',
            field=models.CharField(choices=[('Bangla', 'Bangla_Medium'), ('English', 'English_Version')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not_Available', 'Not Available')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='tutorreview',
            name='rating',
            field=models.CharField(choices=[('⭐', '1_Star'), ('⭐⭐', '2_Stars'), ('⭐⭐⭐', '3_Stars'), ('⭐⭐⭐⭐', '4_Stars'), ('⭐⭐⭐⭐⭐', '5_Stars')], max_length=10),
        ),
    ]
