# Generated by Django 5.0.6 on 2024-07-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_alter_subjectchoice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutormodel',
            name='image',
            field=models.ImageField(upload_to='tutor/images/'),
        ),
    ]
