# Generated by Django 5.0.6 on 2024-07-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_alter_tutormodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutormodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tutor/images/'),
        ),
    ]
