# Generated by Django 5.0.6 on 2024-07-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_alter_tutormodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutormodel',
            name='preferred_area_to_teach',
        ),
        migrations.RemoveField(
            model_name='tutormodel',
            name='preferred_class',
        ),
        migrations.RemoveField(
            model_name='tutormodel',
            name='preferred_subjects',
        ),
        migrations.RemoveField(
            model_name='tutormodel',
            name='preferred_time',
        ),
    ]
