# Generated by Django 5.0.6 on 2024-07-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0013_remove_tutormodel_preferred_area_to_teach_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassChoice',
        ),
        migrations.DeleteModel(
            name='SubjectChoice',
        ),
        migrations.DeleteModel(
            name='TimeChoice',
        ),
    ]
