# Generated by Django 5.0.6 on 2024-07-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0014_delete_classchoice_delete_subjectchoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorreview',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='tutorreview',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='TutorEducation',
        ),
        migrations.DeleteModel(
            name='TutorReview',
        ),
    ]
