# Generated by Django 5.0.6 on 2024-07-13 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tution', '0005_alter_subjectchoice_name'),
        ('tutor', '0007_alter_subjectchoice_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('accepted', 'Accepted')], max_length=20)),
                ('tuition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tution.tuition')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.tutormodel')),
            ],
        ),
    ]
