# Generated by Django 5.0.6 on 2024-07-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_for_tution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('accepted', 'Accepted')], default='applied', max_length=20),
        ),
    ]
