# Generated by Django 5.0.6 on 2024-09-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0002_remove_tuition_availability_tuition_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='days',
        ),
        migrations.AlterField(
            model_name='tuition',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tuition',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, to='tuition.dayschoice'),
        ),
    ]
