# Generated by Django 5.0.6 on 2024-09-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_alter_tuition_days_alter_tuition_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='preferred_tutor_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Preferred gender of tutor', max_length=50),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='student_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Gender of students', max_length=50),
        ),
    ]
