# Generated by Django 5.0.6 on 2024-09-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentmodel_gender'),
        ('tuition', '0005_alter_tuition_preferred_tutor_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmodel'),
        ),
    ]
