# Generated by Django 5.0.6 on 2024-09-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0009_rename_created_review_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuition',
            name='days',
        ),
        migrations.DeleteModel(
            name='DaysChoice',
        ),
    ]
