# Generated by Django 5.0.6 on 2024-10-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0010_remove_tuition_days_delete_dayschoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='salary',
            field=models.PositiveIntegerField(blank=True, help_text='Salary offered per month', null=True),
        ),
    ]
